# Generated by Django 5.2.4 on 2025-08-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id_cronograma', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
            options={
                'db_table': 'cronograma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaHistorico',
            fields=[
                ('id_factura_historico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('comprobante_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_producto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'detalle_factura_historico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('proceso_pedido', models.CharField(choices=[('preparando', 'Preparando'), ('empaquetando', 'Empaquetando'), ('en entrega', 'En entrega'), ('completado', 'Completado')], max_length=20)),
                ('estado_pedido', models.CharField(choices=[('por validar', 'Por validar'), ('aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], max_length=20)),
            ],
            options={
                'db_table': 'estado_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('comprobante_archivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favoritos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField()),
                ('fecha_agregado', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, max_length=255, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('imagen_public_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('rol', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoraciones',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_valoracion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'valoraciones',
                'managed': False,
            },
        ),
    ]
