# Generated by Django 5.2.4 on 2025-08-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('proceso_pedido', models.CharField(max_length=50)),
                ('estado_pedido', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_factura',
                'managed': False,
            },
        ),
    ]
